import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/components/NavbarWrapper"; // client-side component
import Footer from "@/components/common/Footer";
// import { Toaster } from 'sonner'
import FluidCursor from "@/components/FluidCursor"; // client-side component
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <FluidCursor />

        <NavbarWrapper /> {/* client-side navbar */}

        {children}
        {/* <Toaster position="top-right" richColors /> */}
        <section className="relative z-10 bg-[#f5f5f5]">
          <Footer />
        </section>
      </body>
    </html>
  );
}
